mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.entites

dept:
  provider:
    name: MICROSERVICECLOUD-DEPT