server:
  port: 8003

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB03
    username: root
    password: ROOT1234
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-idle: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka, http://eureka2.com:7002/eureka, http://eureka3.com:7003/eureka
  instance:
    instance-id: deptProvider8003
    prefer-ip-address: true
info:
  build.artifactId: $project.artifactId$。
  build.version: $project.version$
