server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka, http://eureka2.com:7002/eureka, http://eureka3.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  routes:
    deptService:
      serviceId: microservicecloud-dept
      path: /deptService/**
    deptService2:
      serviceId: microservicecloud-dept2
      path: /microservicecloud-dept/**
  # 忽略所有注册原服务名称，也可用具体的serviceName多个逗号分隔
  ignored-services: "*"
  # 网关统一公共前缀
  prefix: /prefix